# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MindValleyiOSChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MindValleyiOSChallenge

   pod 'LGRefreshView', '~> 1.0.0'

   pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'

   pod 'PromiseKit', '~> 6.0'
   
   pod 'MBProgressHUD', '~> 1.1.0'
   
   pod 'IQKeyboardManager'

   pod 'SideMenu'

  target 'MindValleyiOSChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MindValleyiOSChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
